version: "3"
services:
  db-dev:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4dev$
    volumes:
      - mysql-dev:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api-dev:
    build:
      context: "api"
    environment:
      DATABASE_URL: "mysql+pymysql://admin:db4dev$@db-dev/db"
    ports:
      - "8081:5000"
    depends_on:
      - db-dev
  
volumes:
  mysql-dev: