version: "3"
services:
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: db4test$
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4test$
    volumes:
      - db-test:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: "api"
    environment:
      DATABASE_URL: "mysql+pymysql://admin:db4test$@db/db"
    ports:
      - "8082:5000"
    depends_on:
      - db
  
volumes:
  db-test: